### ISSUE TITLE
Incorrect output of test

### ISSUE THREAD

**Issue by apocalypsetank** [Lornatang/ESPCN-PyTorch#1]
I used the command :"python test_image.py --file ./assets/baby.png --scale-factor 2 ---weights ./weights/espcn_2x.pth -cuda "to test the model ,and I found that the output is X4 upscaled instead of X2. Actually X4 model slao upscale the input to X8.Could you please tell me the reason ,if i used your code in an incorrect way.

**Comment by Lornatang** [comment]
I think you may have the wrong code.

**Comment by apocalypsetank** [comment]
I found the code may not correct , line 55-57 in test_image.py  seems unnecessary. Could you tell me your reason for the upsample? Thank you!

**Comment by Lornatang** [comment]
Because espcn only reconstructs y channel, it is actually similar to fsrcnn. In the end, we need to fuse Cr and Cb images in YCrCb, but we have not reconstructed Cr and Cb images, so we need to enlarge the length and width

**Comment by apocalypsetank** [comment]
The code seems to upscale the Cr and Cb twice, line 83-84 upscale the  Cr and Cb too.Line 55-57 seems unnecessary and incorrect, because line 55-57 seems to upscale the input of net .

**Comment by Lornatang** [comment]
Can you post your code?

**Comment by apocalypsetank** [comment]
The same as your code.
https://github.com/Lornatang/ESPCN-PyTorch/blob/main/test_image.py.
line 55-57: 
image_width = int(image.size[0] * args.scale_factor)
image_height = int(image.size[1] * args.scale_factor)
image = image.resize((image_width, image_height), Image.BICUBIC)
line 73-74:
out_img_cb = cb.resize(out_image_y.size, Image.BICUBIC)
out_img_cr = cr.resize(out_image_y.size, Image.BICUBIC)

Actually, you upscale the input twice.

**Comment by Lornatang** [comment]
OK,Thank you.
